# Generated by Django 5.1.2 on 2026-03-10 09:32

import verification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='public_token',
            field=models.CharField(db_index=True, default=verification.models._generate_public_token, max_length=200, unique=True),
        ),
    ]
