# Generated by Django 4.2.29 on 2026-03-11 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_verificationrequest_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAssetPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=verification.models._verification_photo_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='verification.verificationrequestasset')),
            ],
            options={
                'db_table': 'verification_asset_photo',
            },
        ),
    ]
