# Generated by Django 4.2.29 on 2026-03-12 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid
import verification.models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_verificationassetphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssetReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('missing', 'Missing Asset'), ('misplaced', 'Misplaced Asset'), ('unlisted', 'Unlisted / Extra Asset Found')], max_length=20)),
                ('asset_name', models.CharField(max_length=300)),
                ('asset_id_if_known', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_description', models.CharField(blank=True, max_length=500, null=True)),
                ('expected_location', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'verification_employee_asset_report',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('otp_verified', 'OTP Verified'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('correction_requested', 'Correction Requested'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=verification.models._employee_report_photo_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='verification.employeeassetreport')),
            ],
            options={
                'db_table': 'verification_employee_report_photo',
            },
        ),
        migrations.AddField(
            model_name='employeeassetreport',
            name='verification_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reports', to='verification.verificationrequest'),
        ),
    ]
