# Generated by Django 4.2.29 on 2026-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_assetverificationresponse_admin_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetverificationresponse',
            name='admin_review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('correction_required', 'Correction Required'), ('missing', 'Missing')], db_index=True, default='pending_review', max_length=20),
        ),
    ]
