# Generated by Django 4.2.29 on 2026-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_alter_assetverificationresponse_admin_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='request_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('delta', 'Delta'), ('reverification', 'Reverification')], db_index=True, default='initial', max_length=20),
        ),
    ]
