# Generated by Django 5.1.2 on 2026-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_fix_image_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('damage', 'Damage'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
